from enum import StrEnum

class TCP_EVENT(StrEnum):
    APP_PASSIVE_OPEN = 'APP_PASSIVE_OPEN'
    APP_ACTIVE_OPEN = 'APP_ACTIVE_OPEN'
    APP_SEND = 'APP_SEND'
    APP_CLOSE = 'APP_CLOSE'
    APP_TIMEOUT = 'APP_TIMEOUT'
    RCV_SYN = 'RCV_SYN'
    RCV_ACK = 'RCV_ACK'
    RCV_SYN_ACK = 'RCV_SYN_ACK'
    RCV_FIN = 'RCV_FIN'
    RCV_FIN_ACK = 'RCV_FIN_ACK'

class TCP_STATE(StrEnum):
    CLOSED = 'CLOSED'
    LISTEN = 'LISTEN'
    SYN_SENT = 'SYN_SENT'
    SYN_RCVD = 'SYN_RCVD'
    ESTABLISHED = 'ESTABLISHED'
    CLOSE_WAIT = 'CLOSE_WAIT'
    LAST_ACK = 'LAST_ACK'
    FIN_WAIT_1 = 'FIN_WAIT_1'
    FIN_WAIT_2 = 'FIN_WAIT_2'
    CLOSING = 'CLOSING'
    TIME_WAIT = 'TIME_WAIT'
    ERROR = 'ERROR'

TCP_TRANSITION = {
    (TCP_STATE.CLOSED, TCP_EVENT.APP_PASSIVE_OPEN): TCP_STATE.LISTEN,
    (TCP_STATE.CLOSED, TCP_EVENT.APP_ACTIVE_OPEN): TCP_STATE.SYN_SENT,
    (TCP_STATE.LISTEN, TCP_EVENT.RCV_SYN): TCP_STATE.SYN_RCVD,
    (TCP_STATE.LISTEN, TCP_EVENT.APP_SEND): TCP_STATE.SYN_SENT,
    (TCP_STATE.LISTEN, TCP_EVENT.APP_CLOSE): TCP_STATE.CLOSED,
    (TCP_STATE.SYN_RCVD, TCP_EVENT.APP_CLOSE): TCP_STATE.FIN_WAIT_1,
    (TCP_STATE.SYN_RCVD, TCP_EVENT.RCV_ACK): TCP_STATE.ESTABLISHED,
    (TCP_STATE.SYN_SENT, TCP_EVENT.RCV_SYN): TCP_STATE.SYN_RCVD,
    (TCP_STATE.SYN_SENT, TCP_EVENT.RCV_SYN_ACK): TCP_STATE.ESTABLISHED,
    (TCP_STATE.SYN_SENT, TCP_EVENT.APP_CLOSE): TCP_STATE.CLOSED,
    (TCP_STATE.ESTABLISHED, TCP_EVENT.APP_CLOSE): TCP_STATE.FIN_WAIT_1,
    (TCP_STATE.ESTABLISHED, TCP_EVENT.RCV_FIN): TCP_STATE.CLOSE_WAIT,
    (TCP_STATE.FIN_WAIT_1, TCP_EVENT.RCV_FIN): TCP_STATE.CLOSING,
    (TCP_STATE.FIN_WAIT_1, TCP_EVENT.RCV_FIN_ACK): TCP_STATE.TIME_WAIT,
    (TCP_STATE.FIN_WAIT_1, TCP_EVENT.RCV_ACK): TCP_STATE.FIN_WAIT_2,
    (TCP_STATE.CLOSING, TCP_EVENT.RCV_ACK): TCP_STATE.TIME_WAIT,
    (TCP_STATE.FIN_WAIT_2, TCP_EVENT.RCV_FIN): TCP_STATE.TIME_WAIT,
    (TCP_STATE.TIME_WAIT, TCP_EVENT.APP_TIMEOUT): TCP_STATE.CLOSED,
    (TCP_STATE.CLOSE_WAIT, TCP_EVENT.APP_CLOSE): TCP_STATE.LAST_ACK,
    (TCP_STATE.LAST_ACK, TCP_EVENT.RCV_ACK): TCP_STATE.CLOSED,
}


def traverse_TCP_states(events: list[TCP_EVENT]) -> TCP_STATE:
    """https://www.codewars.com/kata/54acc128329e634e9a000362/train/python"""
    state = TCP_STATE.CLOSED
    for event in events:
        next_state = TCP_TRANSITION.get((state, event))
        if next_state is None:
            return TCP_STATE.ERROR
        state = next_state

    return next_state
